[package]
name = "Formatter"
version = "0.1.0"
authors = ["matsse <56912685+matsse@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.7"